name: prompt-playground
channels:
  - conda-forge
dependencies:
  - annotated-types=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2024.7.4
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcxx=18.1.8
  - libexpat=2.6.2
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - liblapack=3.9.0
  - libopenblas=0.3.27
  - libsqlite=3.46.0
  - libzlib=1.3.1
  - llvm-openmp=18.1.8
  - ncurses=6.5
  - numpy=2.0.1
  - openssl=3.3.1
  - pandas=2.2.2
  - pip=24.0
  - pydantic=2.8.2
  - pydantic-core=2.20.1
  - python=3.11.9
  - python-dateutil=2.9.0
  - python-tzdata=2024.1
  - python_abi=3.11
  - pytz=2024.1
  - readline=8.2
  - scipy=1.14.0
  - setuptools=71.0.4
  - six=1.16.0
  - tk=8.6.13
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2024a
  - wheel=0.43.0
  - xz=5.2.6
  - pip:
      - anthropic==0.31.2
      - anyio==4.4.0
      - certifi==2024.7.4
      - charset-normalizer==3.3.2
      - distro==1.9.0
      - filelock==3.15.4
      - fsspec==2024.6.1
      - h11==0.14.0
      - httpcore==1.0.5
      - httpx==0.27.0
      - huggingface-hub==0.24.2
      - idna==3.7
      - iniconfig==2.0.0
      - jiter==0.5.0
      - openai==1.37.1
      - packaging==24.1
      - pluggy==1.5.0
      - pytest==8.3.2
      - pyyaml==6.0.1
      - regex==2024.7.24
      - requests==2.32.3
      - sniffio==1.3.1
      - tenacity==8.5.0
      - tiktoken==0.7.0
      - tokenizers==0.19.1
      - tqdm==4.66.4
      - urllib3==2.2.2
