name: CI

on: [push]

jobs:
  test:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        id: cache
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ hashFiles('environment.yml') }}
      - uses: conda-incubator/setup-miniconda@v3
        if: steps.cache.outputs.cache-hit != 'true'
        with:
          auto-update-conda: true
          activate-environment: myenv
          environment-file: environment.yml
          python-version: 3.11
      - run: echo "source activate myenv" >> $GITHUB_ENV
      - name: Test
        shell: bash -l {0}
        run: |
          make test
