name: CI

on: [push]

jobs:
  test:
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        env:
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('environment.yml') }}
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: prompt-playground
          auto-update-conda: true
          python-version: 3.11
          use-only-tar-bz2: true
      - name: Create environment
        run: conda env create -f environment.yml --verbose
      - name: Test
        run: make test
